DROP TABLE IF EXISTS STUDENT_DETAILS;

CREATE TABLE IF NOT EXISTS STUDENT_DETAILS
(
	srno INT PRIMARY KEY,	
	order_id VARCHAR(20),	
	student_name VARCHAR(50),
	payment_date DATE,	
	course_name	VARCHAR(30),
	price NUMERIC,	
	payment_status VARCHAR(15),	
	payment_id	VARCHAR(30),
	email VARCHAR(50),	
	state VARCHAR(30)
);

SELECT * FROM STUDENT_DETAILS;

COPY
STUDENT_DETAILS(srno,order_id,student_name,payment_date,course_name,price,payment_status,payment_id,email,state)
FROM 'D:\SQL\Indian_Students_Data.csv'
DELIMITER','
CSV HEADER;

-- BASIC SQL QUERIES


SELECT * 
FROM STUDENT_DETAILS;


SELECT SRNO, STUDENT_NAME, COURSE_NAME, PRICE
FROM STUDENT_DETAILS;

-- DISPLAY THE RECORDS OF STUDENTS WHOSE COURSE IS SQL

SELECT *
FROM STUDENT_DETAILS
WHERE COURSE_NAME='SQL';


SELECT *
FROM STUDENT_DETAILS
WHERE UPPER(COURSE_NAME)='TALLY PRIME';

SELECT *
FROM STUDENT_DETAILS
WHERE UPPER(STATE)='MAHARASHTRA';


SELECT *
FROM STUDENT_DETAILS
WHERE PAYMENT_DATE<'2024-01-01';

-- COMPARISON OPERATORS
SELECT *
FROM STUDENT_DETAILS
WHERE COURSE_NAME!='Tally Prime';

-- ORDER BY

SELECT * 
FROM STUDENT_DETAILS
ORDER BY STUDENT_NAME;

SELECT * 
FROM STUDENT_DETAILS
WHERE PAYMENT_STATUS = 'captured'
ORDER BY SRNO DESC;


-- LIMIT
SELECT * 
FROM STUDENT_DETAILS
LIMIT 5;

SELECT * 
FROM STUDENT_DETAILS
ORDER BY SRNO DESC
LIMIT 10;

SELECT * 
FROM STUDENT_DETAILS
LIMIT 5 OFFSET 50;


SELECT * 
FROM STUDENT_DETAILS
WHERE SRNO BETWEEN 51 AND 55;


-- SHOW MINIMUM VALUE
SELECT MAX(price) AS maximum_value
FROM STUDENT_DETAILS;

SELECT MIN(price) AS minimum_value
FROM STUDENT_DETAILS;




-- COUNT ALL RECORDS

SELECT COUNT(*)
FROM STUDENT_DETAILS;


-- COUNT RECORDS FROM SPECIFIC COLUMN

SELECT COUNT(STATE)
FROM STUDENT_DETAILS;

-- UNIQUE COUNT

SELECT COUNT(DISTINCT STATE)
FROM STUDENT_DETAILS;


-- FILTER COUNT
SELECT COUNT(*)
FROM STUDENT_DETAILS
WHERE STATE ='Bihar';

SELECT COUNT(*)
FROM STUDENT_DETAILS
WHERE PAYMENT_DATE ='2023-07-01';


-- USE OF SUM
SELECT SUM(price)
FROM STUDENT_DETAILS;


-- USE OF SUM WITH FILTER
SELECT SUM(price)
FROM STUDENT_DETAILS
WHERE PAYMENT_STATUS='captured';



SELECT SUM(price)
FROM STUDENT_DETAILS
WHERE payment_date BETWEEN '2023-12-01' AND '2023-12-31';

--AVG
SELECT AVG(price)
FROM STUDENT_DETAILS;

SELECT AVG(price)::NUMERIC(10,2)
FROM STUDENT_DETAILS;


SELECT * 
FROM STUDENT_DETAILS
WHERE STUDENT_NAME LIKE '%Kumar%';



SELECT * 
FROM STUDENT_DETAILS
WHERE state in ('Maharashtra', 'Bihar', 'Haryana');

SELECT * 
FROM STUDENT_DETAILS
WHERE state='Maharashtra' or state='Bihar';

SELECT * 
FROM STUDENT_DETAILS;









